[project]
name = "github-app"
version = "0.1.0"
description = ""
authors = [
    {name = "carloshob",email = "carloshenrique.ob@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pwdlib[argon2] (>=0.2.1,<0.3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
